debug: true
secret_key: dev-secret-key
database_uri: mysql+pymysql://root:Bing2003@8.155.40.179:3306/psychological_health?charset=utf8mb4
cors_origins: '*'
domain: ""

# 邮箱配置
email:
  smtp_server: smtp.qq.com  # 邮箱服务器地址
  smtp_port: 587            # SMTP端口号
  use_tls: true            # 是否使用TLS加密
  sender_email: "huaqiwill@qq.com"         # 发送方邮箱地址
  sender_password: "anbdmjgjzdnrdced"      # 发送方邮箱密码或授权码
  sender_name: "心理健康平台"  # 发送方显示名称

# Redis配置
redis:
  host: 8.155.40.179
  port: 6379
  db: 0
  password: 'Bing2003'
  decode_responses: true

# Session配置
session:
  type: redis
  permanent: false
  use_signer: true
  key_prefix: 'session:'
  redis_key_prefix: 'session:'
  cookie_httponly: true
  cookie_secure: false
  expires: 7200  # 2小时，单位：秒
