version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    environment:
      # 应用配置
      - FLASK_ENV=production
      - CONFIG_PATH=config-prod.yaml
      
      # 数据库配置 (MySQL)
      - DATABASE_URI=mysql://app_user:app_password@db:3306/psychological_health
      
      # Redis配置
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      
      # 安全配置
      - SECRET_KEY=your-super-secret-key-here
      
      # CORS 配置
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80,https://yourdomain.com
      
      # Gunicorn 配置
      - PORT=5000
      - WORKERS=4
      - TIMEOUT=60
      - KEEP_ALIVE=5
      - MAX_REQUESTS=1000
      - MAX_REQUESTS_JITTER=100
    
    volumes:
      # 持久化上传文件
      - ~/data/psychological-health/uploads:/app/uploads
      - ~/data/psychological-health/static:/app/static
      
      # 持久化数据库 (如果使用 SQLite)
      - ~/data/psychological-health/instance:/app/instance
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Web前端服务
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ~/data/psychological-health/web-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    
    depends_on:
      - backend

  # MySQL 数据库服务
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=psychological_health
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    volumes:
      - ~/data/psychological-health/mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis 会话存储服务
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - ~/data/psychological-health/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    name: psychological_health_network 