DEBUG: false
SECRET_KEY: prod-secret-key-change-me
DATABASE_URI: mysql://user:password@localhost/psychological_health
CORS_ORIGINS: 'https://yourdomain.com'

# Redis配置
REDIS:
  HOST: ${REDIS_HOST:-localhost}
  PORT: ${REDIS_PORT:-6379}
  DB: ${REDIS_DB:-0}
  PASSWORD: ${REDIS_PASSWORD:-null}
  DECODE_RESPONSES: true
  
# Session配置
SESSION:
  TYPE: redis
  PERMANENT: false
  USE_SIGNER: true
  KEY_PREFIX: 'session:'
  REDIS_KEY_PREFIX: 'session:'
  COOKIE_HTTPONLY: true
  COOKIE_SECURE: true
  EXPIRES: 7200  # 2小时，单位：秒 