version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    container_name: mental-health-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mental_health
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mental_health.sql:/docker-entrypoint-initdb.d/mental_health.sql
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always

  redis:
    image: redis:6-alpine
    container_name: mental-health-redis
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: mental-health-app
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: druid
      SPRING_DATASOURCE_DRUID_MASTER_URL: jdbc:mysql://mysql:3306/mental_health?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      SPRING_DATASOURCE_DRUID_MASTER_USERNAME: root
      SPRING_DATASOURCE_DRUID_MASTER_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      RUOYI_PROFILE: /app/upload
    ports:
      - "8089:8089"
    volumes:
      - ./upload:/app/upload
    restart: always

volumes:
  mysql_data: